export const API_ENDPOINTS = {
  LOGIN: "/auth/sign_in",
  REGISTER: "/auth",
  CONFIRMATION: "/auth/confirmation",
  LOGOUT: "/auth/sign_out",
  PRODUCT: "/products/[id]",
  PLANS: "/plans",
  SUBSCRIBE: "/create_subscription",

  // Dummy endpoints
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories.json",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands.json",
  PRODUCTS: "/products.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
  FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
  SHOPS: "/shops.json",
  SHOP: "/shop.json",
  SEARCH: "/search",
  ORDERS: "/orders.json",
  ORDER: "/order.json",
};
