NEXT_PUBLIC_REST_API_ENDPOINT:
  dev: http://localhost:4000/api
NEXT_PUBLIC_SITE_URL:
  dev: http://localhost:3000
NEXT_PUBLIC_GOOGLE_ANALYTICS:
  dev: 
NEXTAUTH_URL:
  dev: 
NEXTAUTH_SECRET:
  dev: 
SIGNING_KEY:
  dev: 
FACEBOOK_ID:
  dev: 
FACEBOOK_SECRET:
  dev: 
GITHUB_ID:
  dev: 
GITHUB_SECRET:
  dev: 
GOOGLE_ID:
  dev: 
GOOGLE_SECRET:
  dev: 
DATABASE_URL:
  dev: postgres://pnovess@localhost:5432/designious_api


